---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

This is a line from RStudio - Carter Wolf this is a line from RStudio - Spenser Leise

Follow the instructions posted at <https://ds202-at-isu.github.io/labs.html> for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.

All submissions to the github repo will be automatically uploaded for grading once the due date is passed. Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

12.1 Step:

-   All of the requirements are met.

12.2 Step:

-   

12.3 Step:

-   The first steps were easy, but upon entering my username and password, I received a message stating, “Failed authentication.” I came across a website that showed you how to obtain a personal token. After receiving the token, I copied and pasted it to the password field and it worked.

12.4 Step:

-   

12.5 Step:

-   

12.6 Step:3

-   
